env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  semi: 0
  linebreak-style: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/order: 0
  arrow-parens: 0
  no-use-before-define: 0
  brace-style: 0
  max-len: 0
  arrow-body-style: 0
  no-new: 0
  object-curly-newline: 0
